<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\ImageIcon.png" />
    <None Remove="Assets\ImageRectangle.jpg" />
    <None Remove="Assets\istockphoto-1369198572-170667a.jpg" />
    <None Remove="Assets\istockphoto-1693405252-612x612.jpg" />
    <None Remove="Assets\polygon.png" />
    <None Remove="ImageTrain\dem-day-sao-vicent-van-gogh.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonConverter.Abstractions" Version="0.13.0" />
    <PackageReference Include="JsonConverter.Newtonsoft.Json" Version="0.13.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\ImageIcon.png" />
    <Resource Include="Assets\ImageRectangle.jpg" />
    <Resource Include="Assets\istockphoto-1369198572-170667a.jpg" />
    <Resource Include="Assets\istockphoto-1693405252-612x612.jpg" />
    <Resource Include="Assets\polygon.png" />
    <Resource Include="ImageTrain\dem-day-sao-vicent-van-gogh.jpg" />
  </ItemGroup>

</Project>
